### ISSUE TITLE
Storyboard Segue Not Performed for SWTableViewCell-based Cells

### ISSUE THREAD

**Issue by davetroy** [CEWendel/SWTableViewCell#109]
If I create a storyboard with a segue to a view controller from a standard UITableViewCell, the segue is automatically performed when the cell is tapped (selected).

Replacing that same UITableViewCell with one that is a subclass of SWTableViewCell (or even a SWTableViewCell), and configuring it per the example, the segue is not triggered.

If I implement `-(void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath` and trigger the segue there, it works.

Is this by design or is there a problem here?

**Comment by simonbromberg** [comment]
Why is that necessary?

Ideally it shouldn't break built-in things like this. Took me a while just to figure out why the segues weren't firing. Having to fire the segue manually defeats the purpose of connecting the segue directly to the cell.
