### ISSUE TITLE
Tags on utility buttons are blown away needlessly

### ISSUE THREAD

**Issue by zygoat** [CEWendel/SWTableViewCell#111]
I have been trying to use -[UIButton tag] as an identifier for acting on button action in my implementation of -swipeableTableViewCell:didTriggerRightUtilityButtonWithIndex:, and was perplexed why the tag I set seemed to never remain in force.

I tracked it down to a simple needless assignment in SWUtilityButtonView.m line 71:

```
    [utilityButton setTag:utilityButtonsCounter];
```

Simply deleting this line solves the problem. I don't know what the intended purpose of this assignment was; nothing in SWTableViewCell or related classes ever appear to read the value from the tag.

Determining the appropriate button action simply based on the button's array index (as espoused by the demo app) is a fragile design; user tags aren't great either, but are a much better approach.

**Comment by infinZero** [comment]
I am able to achieve index path of selected row for segue sender and it is working well 

However I've issue with utility buttons 

How can I access UitlityButtons row's IndexPath whereas I've already tried following.

```
NSIndexPath *indexPath = [self.tableView indexPathForSelectedRow]; 
NSLog(@"selected favourite button tag %ld",(long)indexPath);

```
whereas in simulator it gives me same result each time.

> selected favourite button tag 0


Any solution to get button's "setTag" property to access index path of the row for those utility buttons when pressed just like in normal tableview

**Comment by zygoat** [comment]
I'm having trouble understanding what you're saying. The code you showed here indicates that `self.tableView` has no selected row.

I presume that you are implementing `swipeableTableViewCell:didTriggerRightUtilityButtonWithIndex:` in your delegate. Therein, couldn't you call `[self.tableView indexPathForCell:]`, passing its argument?
