### ISSUE TITLE
Crash in ios 6.x

### ISSUE THREAD

**Issue by caiguo37** [CEWendel/SWTableViewCell#150]
Version > 0.2.7 will crash in iOS 6.x

**Comment by debugly** [comment]
I was solved ：

//SWTableViewCell 
- (void)layoutSubviews
{
   //fix iOS6 crash: “Auto Layout still required after executing -layoutSubviews”
    NSString *systemVersion = [UIDevice currentDevice].systemVersion;
    bool iOS6 = [systemVersion hasPrefix:@"6."];
    if(!iOS6) {
        [super layoutSubviews];
    }
    // Offset the contentView origin so that it appears correctly w/rt the enclosing scroll view (to which we moved it).
    CGRect frame = self.contentView.frame;
    frame.origin.x = [self leftUtilityButtonsWidth];
    _contentCellView.frame = frame;

    self.cellScrollView.contentSize = CGSizeMake(CGRectGetWidth(self.frame) + [self utilityButtonsPadding], CGRectGetHeight(self.frame));

    if (!self.cellScrollView.isTracking && !self.cellScrollView.isDecelerating)
    {
        self.cellScrollView.contentOffset = [self contentOffsetForCellState:_cellState];
    }

    [self updateCellState];

    if(iOS6) {
        [super layoutSubviews];
    }
}

**Comment by debugly** [comment]
I was solved ：

```
//SWTableViewCell 
- (void)layoutSubviews
{
   //fix iOS6 crash: “Auto Layout still required after executing -layoutSubviews”
    NSString *systemVersion = [UIDevice currentDevice].systemVersion;
    bool iOS6 = [systemVersion hasPrefix:@"6."];
    if(!iOS6) {
        [super layoutSubviews];
    }
    // Offset the contentView origin so that it appears correctly w/rt the enclosing scroll view (to which we moved it).
    CGRect frame = self.contentView.frame;
    frame.origin.x = [self leftUtilityButtonsWidth];
    _contentCellView.frame = frame;

    self.cellScrollView.contentSize = CGSizeMake(CGRectGetWidth(self.frame) + [self utilityButtonsPadding], CGRectGetHeight(self.frame));

    if (!self.cellScrollView.isTracking && !self.cellScrollView.isDecelerating)
    {
        self.cellScrollView.contentOffset = [self contentOffsetForCellState:_cellState];
    }

    [self updateCellState];

    if(iOS6) {
        [super layoutSubviews];
    }
}
```
