### ISSUE TITLE
Ability to add custom uiview as utility buttons

### ISSUE THREAD

**Issue by AdiletAbylov** [CEWendel/SWTableViewCell#159]
hey, thank you for a great library.
It would be great to have ability to add custom uiviews as utility buttons.

**Comment by Khronoss** [comment]
Hello :)

I agree with @AdiletAbylov, it would be a really nice feature ! Unfortunately, this issue is closed and you didn't explained why =X Do plan to do it ? Can we actually do it, but the doc isn't update ? Or is it just because you don't plan to do it at all ?

**Comment by simplelife-patrick** [comment]
Hello :)

I also wanna this feature, same with @Khronoss and @AdiletAbylov. Any more explain will be appreciated.
