### ISSUE TITLE
Buggy when combining SW and TableView editing delegate methods

### ISSUE THREAD

**Issue by jeffhatz** [CEWendel/SWTableViewCell#167]
When I'm using just SWTableViewCell, everything works perfectly.

However, when combining it with native UITableViewCell delegate methods for editing functionality, such as tableView:commitEditingStyle:forRowAtIndexPath or tableView:canMoveRowAtIndexPath:, it gets glitchy sometimes.

I'm not doing anything out of the ordinary: tableView:cellForRowAtIndexPath: is setting rightUtilityButtons then the delegate, per the SW sample app. The tableView delegate methods are also pretty straight forward, they simply allow reordering, and deleting. I don't really care about deleting via the tableView delegate since I'm handling that in SW, but I need reordering and delete comes free with that when in edit mode.

It looks like adding this resolves the problem. It would be nice if this "fix" wasn't necessary.
- (UITableViewCellEditingStyle)tableView:(UITableView *)tableView editingStyleForRowAtIndexPath:(NSIndexPath *)indexPath
  {
  return UITableViewCellEditingStyleNone;
  }

Here's what I'm seeing happen:
https://www.dropbox.com/s/rw0m5469m2nelrb/SWTableViewCell.mov

**Comment by karadza3a** [comment]
@nod Have you found a solution for swipe gestures not being recognized?

**Comment by RogyMD** [comment]
A solution: You can implement -respondsToSelector: method in your controller and return NO when is asking about @selector(tableView:commitEditingStyle:forRowAtIndexPath:). Anything like this:

```
-(BOOL)respondsToSelector:(SEL)aSelector {
  if (@selector(tableView:commitEditingStyle:forRowAtIndexPath:) == aSelector) {
    return NO;
  } else {
   return [super respondsToSelector:aSelector];
  }
}
```

**Comment by buttcmd** [comment]
@nod @karadza3a Have you found a solution to this?

**Comment by nod** [comment]
@buttcmd sorry, I actually no longer work on that app.  I don't recall ever coming up with a good solution and ended up rewriting it to use a different lib.
