### ISSUE TITLE
indexPathForSelectedRow not working

### ISSUE THREAD

**Issue by lorenzopicoli** [CEWendel/SWTableViewCell#18]
When using SWTableViewCell the method indexPathForSelectedRow always return nil.

**Comment by infinZero** [comment]
I am able to achieve index path of selected row for segue sender and it is working well 

However I've issue with utility buttons 

How can I access UitlityButtons row's IndexPath whereas I've already tried following.

```
NSIndexPath *indexPath = [self.tableView indexPathForSelectedRow]; 
NSLog(@"selected favourite button tag %ld",(long)indexPath);

```
whereas in simulator it gives me same result each time.

> selected favourite button tag 0


Any solution to get button's "setTag" property to access index path of the row for those utility buttons when pressed just like in normal tableview
