### ISSUE TITLE
the UITableViewCell dosen't response to prepareforsegue function

### ISSUE THREAD

**Issue by duoluo** [CEWendel/SWTableViewCell#240]
I add a modal segue with the prototype cell。But when I use the SWTableViewCell, the prepareForSegue dosen't response.

**Comment by colinhumber** [comment]
Segues hooked up on the cell in the storyboard don't fire when a cell subclasses SWTableViewCell. With standard cells, tapping the cell, when a segue is attached to it, will fire the `-prepareForSegue:` method. When using this, you need to override `-tableView:didSelectRowAtIndexPath:` which is usually not necessary. This should be documented as it overrides the standard system behaviour.
