### ISSUE TITLE
iPhone 6 Bug

### ISSUE THREAD

**Issue by adnanAhmad786** [CEWendel/SWTableViewCell#267]
Cells are not showing in iPhone 6 in iPhone 5c and previous works fine

**Comment by Supertecnoboff** [comment]
@adnanAhmad786 Is this still affecting you?

**Comment by adnanAhmad786** [comment]
Hi,

I have figured it out. Just needed to  put that code in viewdidload and
every thing is works just fine

   self.yourTableView.rowHeight = UITableViewAutomaticDimension;

    self.yourTableView.estimatedRowHeight = your Cell estimated height;

Regards,
Adnan Ahmad

On Sat, Feb 14, 2015 at 10:15 PM, Daniel Sadjadian <notifications@github.com
