### ISSUE TITLE
Similar effect in Android

### ISSUE THREAD

**Issue by niteshkhatri** [CEWendel/SWTableViewCell#276]
First of all nice work. Its pretty impressive. I am planning to implement similar effect in one of my Android Project. Is it possible in Android? How can I achieve this in Android?

Do you know any such library with similar effect on ListViews in Android?

**Comment by heapwalker** [comment]
Hi @niteshkhatri I was looking for the equivalent library for android too. You may find it useful: https://github.com/47deg/android-swipelistview
