### ISSUE TITLE
Background color of 2 buttons overlap creating a  third color

### ISSUE THREAD

**Issue by Ge0rges** [CEWendel/SWTableViewCell#294]
The title is pretty self explanatory, because the buttons apparently don't support nil background colors)(https://github.com/CEWendel/SWTableViewCell/issues/292) I pass a background color to each buttons I have, for some reason there is a small space between each button which the background colors fill the issue is that they overlap creating a third color which is quite visible and ugly. For example one button is green and another blue I get a 3-10 pixel wide yellow line. This may help https://github.com/CEWendel/SWTableViewCell/issues/293.

**Comment by Ge0rges** [comment]
I used the SetRightUtilityButtons: WithWidth: method to fix this issue didn't know it existed.

**Comment by russellbstephens** [comment]
If you want to use a nil color, why not use [UIColor clearColor]?

**Comment by Ge0rges** [comment]
That's a good point but I though adding a background color might add width to the image.
