### ISSUE TITLE
Mistake in Readme

### ISSUE THREAD

**Issue by mrvincenzo** [CEWendel/SWTableViewCell#315]
tableView:cellForRowAtIndexPath: is a method of UITableViewDataSource and not of UITableViewDelegate as stated.

**Comment by CEWendel** [comment]
Fixed now. Good catch :)

On Sun, May 10, 2015 at 5:21 PM, mrvincenzo <notifications@github.com>
wrote:

> tableView:cellForRowAtIndexPath: is a method of UITableViewDataSource and
> not of UITableViewDelegate as stated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CEWendel/SWTableViewCell/issues/315>.
>



-- 
Chris Wendel
University of Michigan '15
Computer Science
