### ISSUE TITLE
Programatically show/hide utility buttons

### ISSUE THREAD

**Issue by mike3k** [CEWendel/SWTableViewCell#348]
There should be a way to bounce the cell or slide it programatically. I'd like to do this the first time the table is shown in my app as a hint to the users that they can slide the cells to reveal extra functions.

**Comment by Ravi61** [comment]
Why was this issue closed? Is there a method to do it?

**Comment by mike3k** [comment]
It can be done by calling showLeftUtilityButtonsAnimated /  showRightUtilityButtonsAnimated and then hideUtilityButtonsAnimated after a delay.

**Comment by Ravi61** [comment]
Thanks 👍
