### ISSUE TITLE
Add a property to change the width of the maximum size of the buttons manually

### ISSUE THREAD

**Issue by rodrigoescobar** [CEWendel/SWTableViewCell#370]
It is very handy that it has a default value but when I have only one element and the text in the cell is short, the default value for the width of the button is too big. It would be awesome if I could change it to whatever width I want

**Comment by heemoe** [comment]
`SWTableViewCell.h`

```
- (void)setRightUtilityButtons:(NSArray *)rightUtilityButtons WithButtonWidth:(CGFloat) width;
- (void)setLeftUtilityButtons:(NSArray *)leftUtilityButtons WithButtonWidth:(CGFloat) width;
```
