### ISSUE TITLE
height of the button

### ISSUE THREAD

**Issue by iHamzaaK** [CEWendel/SWTableViewCell#375]
I need to change the height of the buttons. Help!

@CEWendel

**Comment by werediver** [comment]
Do you want to have buttons height not equal to the cell height? I don't think this feature is worth incorporating the upstream, but surely you can implement it in a fork.

**Comment by iHamzaaK** [comment]
Yeah because my cell view is little small as compared to actual cell height. Can u guide me where u adjusted the button height?
