### ISSUE TITLE
Does not show all the buttons

### ISSUE THREAD

**Issue by bkcan** [CEWendel/SWTableViewCell#391]
It doesn't matter which side the buttons are, but when I swipe it does not show all the buttons. The cell will move to where it's suppose to stop but then bounce back halfway. I'm trying to display three buttons but it will only show 1 and a half.

Also when the last button is pressed, when swiping again the cell goes to the CORRECT spot which is the end of the first button.

Does anyone know how to solve this problem?

**Comment by LeandroGitHung** [comment]
put a CGD... at this line...
    dispatch_async(dispatch_get_main_queue(), ^{

```
    cell.leftUtilityButtons = [self leftButtons];

});
```
