### ISSUE TITLE
How to get "indexPath"?

### ISSUE THREAD

**Issue by giuseppebruno** [CEWendel/SWTableViewCell#400]
How to get `indexPath` when calling `func swipeableTableViewCell(cell: SWTableViewCell!, didTriggerRightUtilityButtonWithIndex index: Int)` in Swift?

**Comment by vinczebalazs** [comment]
You can use 

`[NSIndexPath indexPathWithIndex:index]`

**Comment by infinZero** [comment]
How can I access same(indexPath) in Objective-C? whereas I've already tried following.

```
 NSIndexPath *indexPath = [self.tableView indexPathForSelectedRow];
   NSLog(@"selected favourite button tag %ld",(long)indexPath);

```
whereas in simulator it gives me same result each time. 
> selected favourite button tag 0

Any solution to get button "setTag" property to access index path of the row for that utility buttons are being pressed just like in normal tableview
