### ISSUE TITLE
How to change the height of button?

### ISSUE THREAD

**Issue by ChungMai** [CEWendel/SWTableViewCell#403]
I want to change the height of right button because my conten cell have large padding bottom. Please show me how to change it.

I can change the height of button by editing the constrain in **(void)setUtilityButtons:(NSArray *)utilityButtons WithButtonWidth:(CGFloat)width** method as follows:

``` objective-c
 [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|[button]-bottom-|"
                                                                         options:0L
                                                                         metrics:@{@"bottom":@(8.0)}
                                                                           views:NSDictionaryOfVariableBindings(button)]];
```

Could you please modify your library to support the change of button height?

**Comment by ChungMai** [comment]
I have downloaded the source code and edited it as I need.

**Comment by goel232** [comment]
@ChungMai Hello friend can you help me with how to change the width and height of button ??
at which file I must see it ?

**Comment by ChungMai** [comment]
Hi @goel232 . If you want to change the width of button, the library is supported to change it through function _(void)setUtilityButtons:(NSArray *)utilityButtons WithButtonWidth:(CGFloat)width_

If you want to change the height of button, you must download source code of sample project  (the library is not supported a public method to configure the heigh button), then you will find the **PodFiles** folder on **SWTableViewCell** parent folder. PodFile is where contain all code for the customised view. 
In SWTableViewCell file at _(void)setUtilityButtons:(NSArray *)utilityButtons WithButtonWidth:(CGFloat)width_ (same method to change the width) where you can add the code to change the heigh to how you want. 
Example: you add the following code to change the bottom and top margin of the button - the height is changed as well
 **[self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|-top-[button]-bottom-|"
                                                                         options:0L
                                                                         metrics:@{@"bottom":@(8.0), @"top":@(8.0)}
                                                                           views:NSDictionaryOfVariableBindings(button)]];**
