### ISSUE TITLE
LeftUtilityButtons are always visible on iPad

### ISSUE THREAD

**Issue by aareeph** [CEWendel/SWTableViewCell#406]
Thanks for this library. It's amazing!

I've integrated this library in my project and it works very well on iPhone however for iPad all the rows show Left Buttons on screen load. Is there any fix?

![image](https://cloud.githubusercontent.com/assets/10115810/19597622/1e4570e8-97af-11e6-85f6-bdc55b37129f.jpg)

Thanks!

**Comment by s-hocking** [comment]
I came across this issue as well. It appears to happen only when compiling with the iOS 10 SDK. I think it's related to Apple changing the behaviour of layoutSubviews and/or layoutIfNeeded.

I fixed it by removing the cellScrollView delegate before calling layoutSubviews, and then adding it back afterwards. This prevents scrollViewDidScroll from being called during layoutSubviews, which seems to result in the cell ending up with the incorrect state set. 

In SWTableViewCell.m:

```
- (void)layoutSubviews
{
    self.cellScrollView.delegate = nil;
    [super layoutSubviews];

    // Offset the contentView origin so that it appears correctly w/rt the enclosing scroll view (to which we moved it).
    CGRect frame = self.contentView.frame;
    frame.origin.x = [self leftUtilityButtonsWidth];
    _contentCellView.frame = frame;

    self.cellScrollView.contentSize = CGSizeMake(CGRectGetWidth(self.frame) + [self utilityButtonsPadding], CGRectGetHeight(self.frame));

    if (!self.cellScrollView.isTracking && !self.cellScrollView.isDecelerating)
    {
        self.cellScrollView.contentOffset = [self contentOffsetForCellState:_cellState];
    }

    [self updateCellState];
    self.cellScrollView.delegate = self;
}
```

Works for me...

**Comment by aareeph** [comment]
Thanks a lot @s-hocking, it worked well for me too! :)
