### ISSUE TITLE
iOS14侧滑不生效

### ISSUE THREAD

**Issue by lsq286224380** [CEWendel/SWTableViewCell#433]
iOS14侧滑不生效

**Comment by ChangJian2333** [comment]
[self.contentView superview];// iOS14 加入这行代码可解决此问题
    if (![NSStringFromClass([[self.subviews objectAtIndex:0] class]) isEqualToString:kTableViewCellContentView])
    {
        // iOS 7
        contentViewParent = [self.subviews objectAtIndex:0];
        clipViewParent = self;
    }
