### ISSUE TITLE
Cell Accessory Item

### ISSUE THREAD

**Issue by squiressquire** [CEWendel/SWTableViewCell#55]
When swiping the cells Accessory item (check, disclosure indicator) stats in place and does not move

**Comment by ryanmeisters** [comment]
Sorry for commenting on a old/closed issue, but.. the SWTableViewCell example project has a disclosure indicator that moves with the swiped cell. Did you have to do anything special to get this to work? The disclosure indicator is set in the storyboard and seems to work fine, however, I am doing the same in my project and seeing the behavior described above.
