### ISSUE TITLE
Subclassing SWTableViewCell Causes Cell to Be Empty!

### ISSUE THREAD

**Issue by BigSauce** [CEWendel/SWTableViewCell#59]
I am attempting to subclass SWTableViewCell to gain its capabilities, but when I do, all of my cell's subviews disappear.  All that displays is an empty cell.

What could be causing this issue?

Here is the header for my SWTableViewCell subclass:
![screen shot 2014-01-07 at 11 09 48 am](https://f.cloud.github.com/assets/1718470/1860632/6e1a33fe-77b6-11e3-85c9-35d814581f62.png)

Here is my prototype for my subclass:
![screen shot 2014-01-07 at 11 10 08 am](https://f.cloud.github.com/assets/1718470/1860635/78c09bea-77b6-11e3-872d-fcdae5115079.png)

View hierarchy for my cell prototype:

![screen shot 2014-01-07 at 11 14 34 am](https://f.cloud.github.com/assets/1718470/1860688/1b9a1ac6-77b7-11e3-962d-2e008e75ec03.png)

I specified the Custom Class:
![screen shot 2014-01-07 at 11 10 24 am](https://f.cloud.github.com/assets/1718470/1860638/7d0a0cd6-77b6-11e3-8531-9d10ea2521d4.png)

I specified my reuse identifier
![screen shot 2014-01-07 at 11 10 34 am](https://f.cloud.github.com/assets/1718470/1860640/7eb6b034-77b6-11e3-8fd5-871510f56727.png)

Here is the code that create's my SWTableViewCell subclass.  Note that if I make CourseCell (my subclass) a subclass of UITableViewCell instead of SWTableViewCell and comment out the SWTableViewCell-specific code, it displays fine.
![screen shot 2014-01-07 at 11 11 26 am](https://f.cloud.github.com/assets/1718470/1860644/81c2a3f0-77b6-11e3-8b6b-405fe5659754.png)

Here are the empty cells when I subclass SWTableViewCell:

![screen shot 2014-01-07 at 11 24 22 am](https://f.cloud.github.com/assets/1718470/1860756/45b97d00-77b8-11e3-8223-1496db7bea1c.png)

Here is what it should look like and does look like when I do not subclass SWTableViewCell.

![screen shot 2014-01-07 at 11 27 57 am](https://f.cloud.github.com/assets/1718470/1860791/ba617fd6-77b8-11e3-83a2-e14abe24bfd7.png)

**Comment by Jeroenbb94** [comment]
I'm getting this issue but the `cell.containingTableView` is not there anymore. How can I fix this?
P.s. I'm using Swift
